// <auto-generated />
using System;
using AuthManSys.Infrastructure.Database.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthManSys.Infrastructure.Migrations
{
    [DbContext(typeof(AuthManSysDbContext))]
    [Migration("20291129000000_AddAssignedAtToUserRoles")]
    partial class AddAssignedAtToUserRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // This is a placeholder - the actual model would be very complex
            // Since this is a manual migration, we don't need the full model here
        }
    }
}